name: Deploy to Firebase Functions

on:
  push:
    branches:
      - main
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '20'

    - name: Installing Dependencies
      run: npm install
      working-directory: ./functions

    - name: Set Environment Variables
      run: |
        echo "NODE_ENV=production" >> $GITHUB_ENV
        echo "FIREBASE_SERVICE_ACCOUNT_BASE64=${{ secrets.FIREBASE_SERVICE_ACCOUNT_BASE64 }}" >> $GITHUB_ENV

    - name: Start Firebase Emulators in Background
      run: firebase emulators:start --only firestore &
      working-directory: .
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        
    - name: Wait for Emulators to Start
      run: sleep 15

    - name: Linting
      run: npm run lint
      working-directory: ./functions

    - name: Testing
      run: npm run test
      working-directory: ./functions

    - name: Building
      run: npm run build
      working-directory: ./functions

    - name: Deploy to Firebase
      uses: w9jds/firebase-action@master
      with:
        args: deploy --only functions
      env:
        FIREBASE_TOKEN: ${{ secrets.FIREBASE_TOKEN }}
        PROJECT_ID: ${{ secrets.PROJECT_ID }}
